version: '2'
services:
    yaldaymono-mongodb:
        container_name: yaldaymono-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/yaldayMono/mongodb/:/data/db/
